# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb739d8953f669427d58c7ae4990f6d87fe2774295b7c2d66b2a9d3db839e5f5fbf40a024ba752c8854c725782335e155d269a9c52baafef25048cefac61dadb

test:
  secret_key_base: bfcaacc5540d9d648c7e036f56f6b5f8edaf46876b8f42f247c6677b5f55a58b8dc4894333f138c9e16a715b3f518a1d82d92cf6d19f8993703346ee473d9b41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
